* Boba
~boba~ is a compiler project to learn about implementing type system, code optimization and code generation. It compiles Rust-like source code to x86-64 assembly.
** Build
To build the CLI:
#+BEGIN_SRC shell
  cargo build
#+END_SRC
NOTE: boba requires ~rustc~ version 1.70.0 or newer.
** Usage
#+BEGIN_SRC bash
  Usage: boba [OPTIONS] <FILENAME>

  Arguments:
    <FILENAME>  Name of the file to be compiled

  Options:
    -p, --print-ast  Print the parsed AST
    -h, --help       Print help
    -V, --version    Print version
#+END_SRC

~gcc~ or ~clang~ can be used to link the generated assembly with C standard library (for accessing ~printf()~) and to convert it into an ELF executable.
#+BEGIN_SRC bash
  gcc <FILENAME>.s && ./a.out
#+END_SRC
** Language Documentation
Check [[./language.org][language documentation]] for details about the syntax and semantics of the language.
** Example Programs
The [[./test/][test/]] directory contains a bunch of example programs that can be compiled with this compiler.
* Devlog
An attempt to document my development process:
1. [[https://veera.app/codegen.html][Boba Devlog #0: Compiling Pseudo-Rust to x86 Assembly]]
2. [[https://veera.app/type_checking.html][Boba Devlog #1: Sliding in a Type Checker]]
